### ISSUE TITLE
Warning about deprecation

### ISSUE THREAD

**Issue by kshedstrom** [adcroft/pyGVtools#4]
It seems you want to know about warnings since they've been turned into errors. This is what I'm getting with python 3:
```
gplot prog.nc,e,:,2 --animate
Traceback (most recent call last):
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot", line 937, in <module>
    if __name__ == '__main__': parseCommandLine()
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot", line 118, in parseCommandLine
    createUI(optCmdLineArgs.file_var_slice, optCmdLineArgs)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot", line 170, in createUI
    render(var, args, frame=n+1, elevation=eVar)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot", line 269, in render
    makeGuessAboutCmap(clim=args.clim, colormap=args.colormap)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot", line 747, in makeGuessAboutCmap
    else: plt.set_cmap('spectral')
  File "/import/u/u1/uaf/kshedstrom/.conda/envs/snowdrifts/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2302, in set_cmap
    cmap = cm.get_cmap(cmap)
  File "/import/u/u1/uaf/kshedstrom/.conda/envs/snowdrifts/lib/python3.5/site-packages/matplotlib/cm.py", line 167, in get_cmap
    return cmap_d[name]
  File "/import/u/u1/uaf/kshedstrom/.conda/envs/snowdrifts/lib/python3.5/site-packages/matplotlib/_cm.py", line 1381, in __getitem__
    obj_type="colormap"
  File "/import/u/u1/uaf/kshedstrom/.conda/envs/snowdrifts/lib/python3.5/site-packages/matplotlib/cbook.py", line 136, in warn_deprecated
    warnings.warn(message, mplDeprecation, stacklevel=1)
matplotlib.cbook.MatplotlibDeprecationWarning: The spectral and spectral_r colormap was deprecated in version 2.0. Use nipy_spectral and nipy_spectral_r instead.
```

**Comment by kshedstrom** [comment]
OK, this was easy to fix, as was the next. Do you want a pull request for version 3 changes?
