### ISSUE TITLE
Next problem

### ISSUE THREAD

**Issue by kshedstrom** [adcroft/pyGVtools#5]
```
gplot prog.nc,salt,:,=-100 --animate
Traceback (most recent call last):
  File "/home/kate/ESMG/pyGVtools/gplot", line 937, in <module>
    if __name__ == '__main__': parseCommandLine()
  File "/home/kate/ESMG/pyGVtools/gplot", line 118, in parseCommandLine
    createUI(optCmdLineArgs.file_var_slice, optCmdLineArgs)
  File "/home/kate/ESMG/pyGVtools/gplot", line 170, in createUI
    render(var, args, frame=n+1, elevation=eVar)
  File "/home/kate/ESMG/pyGVtools/gplot", line 183, in render
    var.getData() # Actually read data from file
  File "/home/kate/ESMG/pyGVtools/gplot", line 580, in getData
    d.getData()
  File "/home/kate/ESMG/pyGVtools/gplot", line 483, in getData
    if self.values==None or forceRead: # If the handle is None then the values were created already
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kshedstrom** [comment]
By the way, this is my third problem, one I don't know how to solve.
